export const LOAD_MEASUREMENTS_START = 'LOAD_MEASUREMENTS_START';
export const LOAD_MEASUREMENTS_SUCCESS = 'LOAD_MEASUREMENTS_SUCCESS';
export const LOAD_MEASUREMENTS_FAILURE = 'LOAD_MEASUREMENTS_FAILURE';
